#define COLOR_ALICEBLUE             0xF0F8FFFF
#define COLOR_ANTIQUEWHITE          0xFAEBD7FF
#define COLOR_AQUA                  0x00FFFFFF
#define COLOR_AQUAMARINE            0x7FFFD4FF
#define COLOR_AZURE                 0xF0FFFFFF
#define COLOR_BEIGE                 0xF5F5DCFF
#define COLOR_BISQUE                0xFFE4C4FF
#define COLOR_BLACK                 0x000000FF
#define COLOR_BLANCHEDALMOND        0xFFEBCDFF
#define COLOR_BLUE                  0x0000FFFF
#define COLOR_BLUEVIOLET            0x8A2BE2FF
#define COLOR_BROWN                 0xA52A2AFF
#define COLOR_BURLYWOOD             0xDEB887FF
#define COLOR_CADETBLUE             0x5F9EA0FF
#define COLOR_CHARTREUSE            0x7FFF00FF
#define COLOR_CHOCOLATE             0xD2691EFF
#define COLOR_CORAL                 0xFF7F50FF
#define COLOR_CORNFLOWERBLUE        0x6495EDFF
#define COLOR_CORNSILK              0xFFF8DCFF
#define COLOR_CRIMSON               0xDC143CFF
#define COLOR_CYAN                  0x00FFFFFF
#define COLOR_DARKBLUE              0x00008BFF
#define COLOR_DARKCYAN              0x008B8BFF
#define COLOR_DARKGOLDENROD         0xB8860BFF
#define COLOR_DARKGRAY              0xA9A9A9FF
#define COLOR_DARKGREY              0xA9A9A9FF
#define COLOR_DARKGREEN             0x006400FF
#define COLOR_DARKKHAKI             0xBDB76BFF
#define COLOR_DARKMAGENTA           0x8B008BFF
#define COLOR_DARKOLIVEGREEN        0x556B2FFF
#define COLOR_DARKORANGE            0xFF8C00FF
#define COLOR_DARKORCHID            0x9932CCFF
#define COLOR_DARKRED               0x8B0000FF
#define COLOR_DARKSALMON            0xE9967AFF
#define COLOR_DARKSEAGREEN          0x8FBC8FFF
#define COLOR_DARKSLATEBLUE         0x483D8BFF
#define COLOR_DARKSLATEGRAY         0x2F4F4FFF
#define COLOR_DARKSLATEGREY         0x2F4F4FFF
#define COLOR_DARKTURQUOISE         0x00CED1FF
#define COLOR_DARKVIOLET            0x9400D3FF
#define COLOR_DEEPPINK              0xFF1493FF
#define COLOR_DEEPSKYBLUE           0x00BFFFFF
#define COLOR_DIMGRAY               0x696969FF
#define COLOR_DIMGREY               0x696969FF
#define COLOR_DODGERBLUE            0x1E90FFFF
#define COLOR_FIREBRICK             0xB22222FF
#define COLOR_FLORALWHITE           0xFFFAF0FF
#define COLOR_FORESTGREEN           0x228B22FF
#define COLOR_FUCHSIA               0xFF00FFFF
#define COLOR_GAINSBORO             0xDCDCDCFF
#define COLOR_GHOSTWHITE            0xF8F8FFFF
#define COLOR_GOLD                  0xFFD700FF
#define COLOR_GOLDENROD             0xDAA520FF
#define COLOR_GRAY                  0x808080FF
#define COLOR_GREY                  0x808080FF
#define COLOR_GREEN                 0x008000FF
#define COLOR_GREENYELLOW           0xADFF2FFF
#define COLOR_HONEYDEW              0xF0FFF0FF
#define COLOR_HOTPINK               0xFF69B4FF
#define COLOR_INDIANRED             0xCD5C5CFF
#define COLOR_INDIGO                0x4B0082FF
#define COLOR_IVORY                 0xFFFFF0FF
#define COLOR_KHAKI                 0xF0E68CFF
#define COLOR_LAVENDER              0xE6E6FAFF
#define COLOR_LAVENDERBLUSH         0xFFF0F5FF
#define COLOR_LAWNGREEN             0x7CFC00FF
#define COLOR_LEMONCHIFFON          0xFFFACDFF
#define COLOR_LIGHTRED              0xFF6347FF
#define COLOR_LIGHTBLUE             0xADD8E6FF
#define COLOR_LIGHTCORAL            0xF08080FF
#define COLOR_LIGHCYAN              0xE0FFFFFF
#define COLOR_LIGHTGOLDENRODYELLOW  0xFAFAD2FF
#define COLOR_LIGHTGRAY             0xD3D3D3FF
#define COLOR_LIGHTGREY             0xD3D3D3FF
#define COLOR_LIGHTGREEN            0x90EE90FF
#define COLOR_LIGHTPINK             0xFFB6C1FF
#define COLOR_LIGHTSALMON           0xFFA07AFF
#define COLOR_LIGHTSEAGREEN         0x20B2AAFF 
#define COLOR_LIGHTSKYBLUE          0x87CEFAFF
#define COLOR_LIGHTSLATEGRAY        0x778899FF
#define COLOR_LIGHTSLATEGREY        0x778899FF
#define COLOR_LIGHTSTEELBLUE        0xB0C4DEFF
#define COLOR_LIGHTYELLOW           0xFFFFE0FF
#define COLOR_LIME                  0x00FF00FF
#define COLOR_LIMEGREEN             0x32CD32FF
#define COLOR_LINEN                 0xFAF0E6FF
#define COLOR_MAGENTA               0xFF00FFFF
#define COLOR_MAROON                0x800000FF
#define COLOR_MEDIUMAQUAMARINE      0x66CDAAFF
#define COLOR_MEDIUMBLUE            0x0000CDFF
#define COLOR_MEDIUMORCHID          0xBA55D3FF
#define COLOR_MEDIUMPURPLE          0x9370DBFF
#define COLOR_MEDIUMSEAGREEN        0x3CB371FF
#define COLOR_MEDIUEMSLATEBLUE      0x7B68EEFF
#define COLOR_MEDIUMSPRINGGREEN     0x00FA9AFF
#define COLOR_MEDIUMTURQUOISE       0x48D1CCFF
#define COLOR_MEDIUMVIOLETRED       0xC71585FF
#define COLOR_MIDNIGHTBLUE          0x191970FF
#define COLOR_MINTCREAM             0xF5FFFAFF
#define COLOR_MISTYROSE             0xFFE4E1FF
#define COLOR_MOCCASIN              0xFFE4B5FF
#define COLOR_NAVAJOWHITE           0xFFDEADFF
#define COLOR_NAVY                  0x000080FF
#define COLOR_OLDLACE               0xFDF5E6FF
#define COLOR_OLIVE                 0x808000FF
#define COLOR_OLIVEDRAB             0x6B8E23FF
#define COLOR_ORANGE                0xFFA500FF
#define COLOR_ORANGERED             0xFF4500FF
#define COLOR_ORCHID                0xDA70D6FF
#define COLOR_PALEGOLDENROD         0xEEE8AAFF
#define COLOR_PALEGREEN             0x98FB98FF
#define COLOR_PALETURQUOISE         0xAFEEEEFF
#define COLOR_PALEVIOLETRED         0xDB7093FF
#define COLOR_PAPAYAWHIP            0xFFEFD5FF
#define COLOR_PEACHPUFF             0xFFDAB9FF
#define COLOR_PERU                  0xCD853FFF
#define COLOR_PINK                  0xFFC0CBFF
#define COLOR_PLUM                  0xDDA0DDFF
#define COLOR_POWDERBLUE            0xB0E0E6FF
#define COLOR_PURPLE                0x800080FF
#define COLOR_REBECCAPURPLE         0x663399FF
#define COLOR_RED                   0xFF0000FF
#define COLOR_ROSYBROWN             0xBC8F8FFF
#define COLOR_ROYALBLUE             0x4169E1FF
#define COLOR_SADDLEBROWN           0x8B4513FF
#define COLOR_SALMON                0xFA8072FF
#define COLOR_SANDYBROWN            0xF4A460FF
#define COLOR_SEAGREEN              0x2E8B57FF
#define COLOR_SEASHELL              0xFFF5EEFF
#define COLOR_SIENNA                0xA0522DFF
#define COLOR_SILVER                0xC0C0C0FF
#define COLOR_SKYBLUE               0x87CEEBFF
#define COLOR_SLATEBLUE             0x6A5ACDFF
#define COLOR_SLATEGRAY             0x708090FF
#define COLOR_SLATEGREY             0x708090FF
#define COLOR_SNOW                  0xFFFAFAFF
#define COLOR_SPRINGGREEN           0x00FF7FFF
#define COLOR_STEELBLUE             0x4682B4FF
#define COLOR_TAN                   0xD2B48CFF
#define COLOR_TEAL                  0x008080FF
#define COLOR_THISTLE               0xD8BFD9FF
#define COLOR_TOMATO                0xFF6347FF
#define COLOR_TURQUOISE             0x40E0D0FF
#define COLOR_VIOLET                0xEE82EEFF
#define COLOR_WHEAT                 0xF5DEB3FF
#define COLOR_WHITE                 0xFFFFFFFF
#define COLOR_WHITESMOKE            0xF5F5F5FF
#define COLOR_YELLOW                0xFFFF00FF
#define COLOR_YELLOWGREEN           0x9ACD32FF

#define	COLOR_GREY1    				0xE6E6E6FF
#define COLOR_GREY2 				0xC8C8C8FF
#define COLOR_GREY3 				0xAAAAAAFF
#define COLOR_GREY4 				0x8C8C8CFF
#define COLOR_GREY5 				0x6E6E6EFF

#define C_ALICEBLUE                 0xF0F8FF
#define C_ANTIQUEWHITE              0xFAEBD7
#define C_AQUA                      0x00FFFF
#define C_AQUAMARINE                0x7FFFD4
#define C_AZURE                     0xF0FFFF
#define C_BEIGE                     0xF5F5DC
#define C_BISQUE                    0xFFE4C4
#define C_BLACK                     0x000000
#define C_BLANCHEDALMOND            0xFFEBCD
#define C_BLUE                      0x0000FF
#define C_BLUEVIOLET                0x8A2BE2
#define C_BROWN                     0xA52A2A
#define C_BURLYWOOD                 0xDEB887
#define C_CADETBLUE                 0x5F9EA0
#define C_CHARTREUSE                0x7FFF00
#define C_CHOCOLATE                 0xD2691E
#define C_CORAL                     0xFF7F50
#define C_CORNFLOWERBLUE            0x6495ED
#define C_CORNSILK                  0xFFF8DC
#define C_CRIMSON                   0xDC143C
#define C_CYAN                      0x00FFFF
#define C_DARKBLUE                  0x00008B
#define C_DARKCYAN                  0x008B8B
#define C_DARKGOLDENROD             0xB8860B
#define C_DARKGRAY                  0xA9A9A9
#define C_DARKGREY                  0xA9A9A9
#define C_DARKGREEN                 0x006400
#define C_DARKKHAKI                 0xBDB76B
#define C_DARKMAGENTA               0x8B008B
#define C_DARKOLIVEGREEN            0x556B2F
#define C_DARKORANGE                0xFF8C00
#define C_DARKORCHID                0x9932CC
#define C_DARKRED                   0x8B0000
#define C_DARKSALMON                0xE9967A
#define C_DARKSEAGREEN              0x8FBC8F
#define C_DARKSLATEBLUE             0x483D8B
#define C_DARKSLATEGRAY             0x2F4F4F
#define C_DARKSLATEGREY             0x2F4F4F
#define C_DARKTURQUOISE             0x00CED1
#define C_DARKVIOLET                0x9400D3
#define C_DEEPPINK                  0xFF1493
#define C_DEEPSKYBLUE               0x00BFFF
#define C_DIMGRAY                   0x696969
#define C_DIMGREY                   0x696969
#define C_DODGERBLUE                0x1E90FF
#define C_FIREBRICK                 0xB22222
#define C_FLORALWHITE               0xFFFAF0
#define C_FORESTGREEN               0x228B22
#define C_FUCHSIA                   0xFF00FF
#define C_GAINSBORO                 0xDCDCDC
#define C_GHOSTWHITE                0xF8F8FF
#define C_GOLD                      0xFFD700
#define C_GOLDENROD                 0xDAA520
#define C_GRAY                      0x808080
#define C_GREY                      0x808080
#define C_GREEN                     0x008000
#define C_GREENYELLOW               0xADFF2F
#define C_HONEYDEW                  0xF0FFF0
#define C_HOTPINK                   0xFF69B4
#define C_INDIANRED                 0xCD5C5C
#define C_INDIGO                    0x4B0082
#define C_IVORY                     0xFFFFF0
#define C_KHAKI                     0xF0E68C
#define C_LAVENDER                  0xE6E6FA
#define C_LAVENDERBLUSH             0xFFF0F5
#define C_LAWNGREEN                 0x7CFC00
#define C_LEMONCHIFFON              0xFFFACD
#define C_LIGHTBLUE                 0xADD8E6
#define C_LIGHTCORAL                0xF08080
#define C_LIGHCYAN                  0xE0FFFF
#define C_LIGHTGOLDENRODYELLOW      0xFAFAD2
#define C_LIGHTGRAY                 0xD3D3D3
#define C_LIGHTGREY                 0xD3D3D3
#define C_LIGHTGREEN                0x90EE90
#define C_LIGHTPINK                 0xFFB6C1
#define C_LIGHTSALMON               0xFFA07A
#define C_LIGHTSEAGREEN             0x20B2AA 
#define C_LIGHTSKYBLUE              0x87CEFA
#define C_LIGHTSLATEGRAY            0x778899
#define C_LIGHTSLATEGREY            0x778899
#define C_LIGHTSTEELBLUE            0xB0C4DE
#define C_LIGHTYELLOW               0xFFFFE0
#define C_LIME                      0x00FF00
#define C_LIMEGREEN                 0x32CD32
#define C_LINEN                     0xFAF0E6
#define C_MAGENTA                   0xFF00FF
#define C_MAROON                    0x800000
#define C_MEDIUMAQUAMARINE          0x66CDAA
#define C_MEDIUMBLUE                0x0000CD
#define C_MEDIUMORCHID              0xBA55D3
#define C_MEDIUMPURPLE              0x9370DB
#define C_MEDIUMSEAGREEN            0x3CB371
#define C_MEDIUEMSLATEBLUE          0x7B68EE
#define C_MEDIUMSPRINGGREEN         0x00FA9A
#define C_MEDIUMTURQUOISE           0x48D1CC
#define C_MEDIUMVIOLETRED           0xC71585
#define C_MIDNIGHTBLUE              0x191970
#define C_MINTCREAM                 0xF5FFFA
#define C_MISTYROSE                 0xFFE4E1
#define C_MOCCASIN                  0xFFE4B5
#define C_NAVAJOWHITE               0xFFDEAD
#define C_NAVY                      0x000080
#define C_OLDLACE                   0xFDF5E6
#define C_OLIVE                     0x808000
#define C_OLIVEDRAB                 0x6B8E23
#define C_ORANGE                    0xFFA500
#define C_ORANGERED                 0xFF4500
#define C_ORCHID                    0xDA70D6
#define C_PALEGOLDENROD             0xEEE8AA
#define C_PALEGREEN                 0x98FB98
#define C_PALETURQUOISE             0xAFEEEE
#define C_PALEVIOLETRED             0xDB7093
#define C_PAPAYAWHIP                0xFFEFD5
#define C_PEACHPUFF                 0xFFDAB9
#define C_PERU                      0xCD853F
#define C_PINK                      0xFFC0CB
#define C_PLUM                      0xDDA0DD
#define C_POWDERBLUE                0xB0E0E6
#define C_PURPLE                    0x800080
#define C_REBECCAPURPLE             0x663399
#define C_RED                       0xFF0000
#define C_ROSYBROWN                 0xBC8F8F
#define C_ROYALBLUE                 0x4169E1
#define C_SADDLEBROWN               0x8B4513
#define C_SALMON                    0xFA8072
#define C_SANDYBROWN                0xF4A460
#define C_SEAGREEN                  0x2E8B57
#define C_SEASHELL                  0xFFF5EE
#define C_SIENNA                    0xA0522D
#define C_SILVER                    0xC0C0C0
#define C_SKYBLUE                   0x87CEEB
#define C_SLATEBLUE                 0x6A5ACD
#define C_SLATEGRAY                 0x708090
#define C_SLATEGREY                 0x708090
#define C_SNOW                      0xFFFAFA
#define C_SPRINGGREEN               0x00FF7F
#define C_STEELBLUE                 0x4682B4
#define C_TAN                       0xD2B48C
#define C_TEAL                      0x008080
#define C_THISTLE                   0xD8BFD9
#define C_TOMATO                    0xFF6347
#define C_TURQUOISE                 0x40E0D0
#define C_VIOLET                    0xEE82EE
#define C_WHEAT                     0xF5DEB3
#define C_WHITE                     0xFFFFFF
#define C_WHITESMOKE                0xF5F5F5
#define C_YELLOW                    0xFFFF00
#define C_YELLOWGREEN               0x9ACD32

#define COL_ALICEBLUE               "{F0F8FF}"
#define COL_ANTIQUEWHITE            "{FAEBD7}"
#define COL_AQUA                    "{00FFFF}"
#define COL_AQUAMARINE              "{7FFFD4}"
#define COL_AZURE                   "{F0FFFF}"
#define COL_BEIGE                   "{F5F5DC}"
#define COL_BISQUE                  "{FFE4C4}"
#define COL_BLACK                   "{000000}"
#define COL_BLANCHEDALMOND          "{FFEBCD}"
#define COL_BLUE                    "{0000FF}"
#define COL_BLUEVIOLET              "{8A2BE2}"
#define COL_BROWN                   "{A52A2A}"
#define COL_BURLYWOOD               "{DEB887}"
#define COL_CADETBLUE               "{5F9EA0}"
#define COL_CHARTREUSE              "{7FFF00}"
#define COL_CHOCOLATE               "{D2691E}"
#define COL_CORAL                   "{FF7F50}"
#define COL_CORNFLOWERBLUE          "{6495ED}"
#define COL_CORNSILK                "{FFF8DC}"
#define COL_CRIMSON                 "{DC143C}"
#define COL_CYAN                    "{00FFFF}"
#define COL_DARKBLUE                "{00008B}"
#define COL_DARKCYAN                "{008B8B}"
#define COL_DARKGOLDENROD           "{B8860B}"
#define COL_DARKGRAY                "{A9A9A9}"
#define COL_DARKGREY                "{A9A9A9}"
#define COL_DARKGREEN               "{006400}"
#define COL_DARKKHAKI               "{BDB76B}"
#define COL_DARKMAGENTA             "{8B008B}"
#define COL_DARKOLIVEGREEN          "{556B2F}"
#define COL_DARKORANGE              "{FF8C00}"
#define COL_DARKORCHID              "{9932CC}"
#define COL_DARKRED                 "{8B0000}"
#define COL_DARKSALMON              "{E9967A}"
#define COL_DARKSEAGREEN            "{8FBC8F}"
#define COL_DARKSLATEBLUE           "{483D8B}"
#define COL_DARKSLATEGRAY           "{2F4F4F}"
#define COL_DARKSLATEGREY           "{2F4F4F}"
#define COL_DARKTURQUOISE           "{00CED1}"
#define COL_DARKVIOLET              "{9400D3}"
#define COL_DEEPPINK                "{FF1493}"
#define COL_DEEPSKYBLUE             "{00BFFF}"
#define COL_DIMGRAY                 "{696969}"
#define COL_DIMGREY                 "{696969}"
#define COL_DODGERBLUE              "{1E90FF}"
#define COL_FIREBRICK               "{B22222}"
#define COL_FLORALWHITE             "{FFFAF0}"
#define COL_FORESTGREEN             "{228B22}"
#define COL_FUCHSIA                 "{FF00FF}"
#define COL_GAINSBORO               "{DCDCDC}"
#define COL_GHOSTWHITE              "{F8F8FF}"
#define COL_GOLD                    "{FFD700}"
#define COL_GOLDENROD               "{DAA520}"
#define COL_GRAY                    "{808080}"
#define COL_GREY                    "{808080}"
#define COL_GREEN                   "{008000}"
#define COL_GREENYELLOW             "{ADFF2F}"
#define COL_HONEYDEW                "{F0FFF0}"
#define COL_HOTPINK                 "{FF69B4}"
#define COL_INDIANRED               "{CD5C5C}"
#define COL_INDIGO                  "{4B0082}"
#define COL_IVORY                   "{FFFFF0}"
#define COL_KHAKI                   "{F0E68C}"
#define COL_LAVENDER                "{E6E6FA}"
#define COL_LAVENDERBLUSH           "{FFF0F5}"
#define COL_LAWNGREEN               "{7CFC00}"
#define COL_LEMONCHIFFON            "{FFFACD}"
#define COL_LIGHTBLUE               "{ADD8E6}"
#define COL_LIGHTCORAL              "{F08080}"
#define COL_LIGHCYAN                "{E0FFFF}"
#define COL_LIGHTGOLDENRODYELLOW    "{FAFAD2}"
#define COL_LIGHTGRAY               "{D3D3D3}"
#define COL_LIGHTGREY               "{D3D3D3}"
#define COL_LIGHTGREEN              "{90EE90}"
#define COL_LIGHTPINK               "{FFB6C1}"
#define COL_LIGHTSALMON             "{FFA07A}"
#define COL_LIGHTSEAGREEN           "{20B2AA}" 
#define COL_LIGHTSKYBLUE            "{87CEFA}"
#define COL_LIGHTSLATEGRAY          "{778899}"
#define COL_LIGHTSLATEGREY          "{778899}"
#define COL_LIGHTSTEELBLUE          "{B0C4DE}"
#define COL_LIGHTYELLOW             "{FFFFE0}"
#define COL_LIME                    "{00FF00}"
#define COL_LIMEGREEN               "{32CD32}"
#define COL_LINEN                   "{FAF0E6}"
#define COL_MAGENTA                 "{FF00FF}"
#define COL_MAROON                  "{800000}"
#define COL_MEDIUMAQUAMARINE        "{66CDAA}"
#define COL_MEDIUMBLUE              "{0000CD}"
#define COL_MEDIUMORCHID            "{BA55D3}"
#define COL_MEDIUMPURPLE            "{9370DB}"
#define COL_MEDIUMSEAGREEN          "{3CB371}"
#define COL_MEDIUEMSLATEBLUE        "{7B68EE}"
#define COL_MEDIUMSPRINGGREEN       "{00FA9A}"
#define COL_MEDIUMTURQUOISE         "{48D1CC}"
#define COL_MEDIUMVIOLETRED         "{C71585}"
#define COL_MIDNIGHTBLUE            "{191970}"
#define COL_MINTCREAM               "{F5FFFA}"
#define COL_MISTYROSE               "{FFE4E1}"
#define COL_MOCCASIN                "{FFE4B5}"
#define COL_NAVAJOWHITE             "{FFDEAD}"
#define COL_NAVY                    "{000080}"
#define COL_OLDLACE                 "{FDF5E6}"
#define COL_OLIVE                   "{808000}"
#define COL_OLIVEDRAB               "{6B8E23}"
#define COL_ORANGE                  "{FFA500}"
#define COL_ORANGERED               "{FF4500}"
#define COL_ORCHID                  "{DA70D6}"
#define COL_PALEGOLDENROD           "{EEE8AA}"
#define COL_PALEGREEN               "{98FB98}"
#define COL_PALETURQUOISE           "{AFEEEE}"
#define COL_PALEVIOLETRED           "{DB7093}"
#define COL_PAPAYAWHIP              "{FFEFD5}"
#define COL_PEACHPUFF               "{FFDAB9}"
#define COL_PERU                    "{CD853F}"
#define COL_PINK                    "{FFC0CB}"
#define COL_PLUM                    "{DDA0DD}"
#define COL_POWDERBLUE              "{B0E0E6}"
#define COL_PURPLE                  "{800080}"
#define COL_REBECCAPURPLE           "{663399}"
#define COL_RED                     "{FF0000}"
#define COL_ROSYBROWN               "{BC8F8F}"
#define COL_ROYALBLUE               "{4169E1}"
#define COL_SADDLEBROWN             "{8B4513}"
#define COL_SALMON                  "{FA8072}"
#define COL_SANDYBROWN              "{F4A460}"
#define COL_SEAGREEN                "{2E8B57}"
#define COL_SEASHELL                "{FFF5EE}"
#define COL_SIENNA                  "{A0522D}"
#define COL_SILVER                  "{C0C0C0}"
#define COL_SKYBLUE                 "{87CEEB}"
#define COL_SLATEBLUE               "{6A5ACD}"
#define COL_SLATEGRAY               "{708090}"
#define COL_SLATEGREY               "{708090}"
#define COL_SNOW                    "{FFFAFA}"
#define COL_SPRINGGREEN             "{00FF7F}"
#define COL_STEELBLUE               "{4682B4}"
#define COL_TAN                     "{D2B48C}"
#define COL_TEAL                    "{008080}"
#define COL_THISTLE                 "{D8BFD9}"
#define COL_TOMATO                  "{FF6347}"
#define COL_TURQUOISE               "{40E0D0}"
#define COL_VIOLET                  "{EE82EE}"
#define COL_WHEAT                   "{F5DEB3}"
#define COL_WHITE                   "{FFFFFF}"
#define COL_WHITESMOKE              "{F5F5F5}"
#define COL_YELLOW                  "{FFFF00}"
#define COL_YELLOWGREEN             "{9ACD32}"
