new const nationalities[][] = {
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Argentine",
    "Armenian",
    "Aruban",
    "Australian",
    "Austrian",
    "Belgian",
    "Bolivian",
    "Botswana",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Cambodian",
    "Canadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Costa Rican",
    "Cubans",
    "Czech",
    "Greenlander",
    "Dominican (Republic)",
    "Dutch",
    "Ecuadorian",
    "Egyptian",
    "English",
    "Ethiopian",
    "Finnish Swedish",
    "Filipino",
    "French",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Guatemalan",
    "Haitian",
    "Hungarian",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivoirian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakh",
    "Kenyan",
    "Korean",
    "Kuwaiti",
    "Lao",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Macedonian",
    "Malaysian",
    "Maldivian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Mongolian",
    "Moroccan",
    "New Zealander",
    "Nicaraguan",
    "Nigerien",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palestinian",
    "Paraguayan",
    "Peruvian",
    "Portuguese",
    "Puerto Rican",
    "Romanian",
    "Russian",
    "Samoan",
    "Scott",
    "Serb",
    "Singaporean",
    "Slovak",
    "Somali",
    "South African",
    "Spaniard",
    "Sri Lankan",
    "Swede",
    "Syrian",
    "Taiwanese",
    "Thai",
    "Tibetan",
    "Tunisian",
    "Turk",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbek",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemeni",
    "Zambian",
    "Zimbabwean"
};

nationality_list(){
    static list[MAX_STRING], string[MAX_STRING];
    format(list, MAX_STRING, "");
    for(new i; i < sizeof(nationalities); i++){
        format(string, MAX_STRING, "%s\n", nationalities[i]);
        strcat(list, string);
    }
    return list;
}